#ifndef	__CONFIG_H
#define	__CONFIG_H

//#include "def.h"

#define	SET_SYSCLK_SUPPORT
#define	RTC_TIMER_SUPPORT
#define	INTERRUPT_SUPPORT
#define	HARDWARE_TIMER_SUPPORT
#define	NOR_FLASH_SUPPORT
#define	NAND_FLASH_SUPPORT
#define	IIC_ROM_SUPPORT
#define	SERIAL_DOWNLOAD_SUPPORT
#define	XMODEM_DOWNLOAD_SUPPORT

#define	ETHERNET_SUPPORT
#ifdef	ETHERNET_SUPPORT
	#define	TFTP_DOWNLOAD_SUPPORT
#endif

#ifdef	NOR_FLASH_SUPPORT
	#define	SST39VF160_SUPPORT
#endif

#if defined(NOR_FLASH_SUPPORT) || defined(NAND_FLASH_SUPPORT)
	#define	SAVE_ENV_SUPPORT
#endif

#define	TIMER_FREQ	1000

#define	CMD_SHELL_SUPPORT

#define	DEFAULT_IP_ADDR		((192U<<24)|(168<<16)|(3<<8)|100)
#define	DEFAULT_IP_MASK		(0xffffff00)
#define	DEFAULT_IP_GATE		((192U<<24)|(168<<16)|(3<<8)|1)

#define	SERIAL_PORTS		2
#define	DEFAULT_SERIAL_PORT	0
#define	DEFAULT_SERIAL_BAUD	115200


#define	INTERRUPT_SUPPORT
#define	USB_DOWNLOAD_SUPPORT
#define	SAVE_ENV_IN_NAND

#define	ROM_BASE	0x08000000
#define	ROM_SIZE	SIZE_2M
#define	DRAM_BASE	0x30000000
#define	DRAM_SIZE	SIZE_64M
#define	SDRAM_SIZE64M		1

#define	_MMUTT_SIZE	SIZE_16K

#define	ROM_END			(ROM_BASE + ROM_SIZE)
#define	DRAM_END		(DRAM_BASE + DRAM_SIZE)
#define	BIOS_RUN_ADDR	(DRAM_END - SIZE_256K)
#define	_MMUTT_STARTADDRESS	(DRAM_END - _MMUTT_SIZE)
//#define	_ISR_STARTADDRESS	(_MMUTT_STARTADDRESS-0x100)

#define	BOOT_PARAMS_ADDR	(DRAM_BASE+0x100)
#define	BIOS_SIZE			(SIZE_64K)
#define	BIOS_BASE			(ROM_SIZE-BIOS_SIZE)
#define	BIOS_LOAD			(ROM_SIZE-4)
#define BIOS_ENV_ADDR		(ROM_SIZE-0x200)

#define	DFT_DOWNLOAD_ADDR	(DRAM_BASE + 0x8000)
#define	DFT_INITRD_ADDR		(DRAM_BASE + (DRAM_SIZE>>1))

#if (SERIAL_PORTS>1)
	#define	SERIAL_PORTS_SWITCH
#endif

#endif
